Faster Input/output
Aniruddhmuley2001/cpp-stl-resources- pull request #1
Opened 2020-09-30 14:27 UTC by annkit24

In competitive coding times matter a lot in running code.so i had updated your document by adding two line.hope you like it.

2020-09-30 16:54 UTC, Aniruddhmuley2001 commented
@annkit24 I guess you can add a comment describing why you added the line, so that even beginners understand it in the first go. Appreciate your effort!

2020-09-30 16:55 UTC, Aniruddhmuley2001 requested changes
@annkit24 I guess you can add a comment describing why you added the line, so that even beginners understand it in the first go. Appreciate your effort!

2020-09-30 19:37 UTC, annkit24 commented
I think i had commented in stl's program...and in other one remains to do
that

On Wed, Sep 30, 2020 at 10:26 PM Aniruddh Muley <notifications@github.com>
wrote:

> *@Aniruddhmuley2001* requested changes on this pull request.
>
> @annkit24 <https://github.com/annkit24> I guess you can add a comment
> describing why you added the line, so that even beginners understand it in
> the first go. Appreciate your effort!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Aniruddhmuley2001/cpp-stl-resources-/pull/1#pullrequestreview-499632960>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANY5CQUPIQNXTRG2UI75G5TSINPKJANCNFSM4R7FJQIA>
> .
>

2020-10-01 02:26 UTC, Aniruddhmuley2001 approved these changes

2020-10-01 02:26 UTC, merged